import type { Metadata } from "next";
import { Cormorant_Garamond, Ubuntu, Geist, Geist_Mono } from "next/font/google";
import Navigation from "../components/Navigation"
import Footer from "../components/Footer"

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const geistCormo = Cormorant_Garamond({
  weight: ["400", "700"],
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-ubuntu',
});

export const metadata: Metadata = {
  title: "BrewBase",
  description: "Generated by BrewBase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistCormo.variable} ${ubuntu.variable}  antialiased`}
      >
        <div>
          <Navigation />
          <main className={`${geistCormo.variable}`}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
